version: '3'
services:
  nifi:
    image: apache/nifi
    container_name: nifi_dataenv
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    links:
       - minimal-jupyter-notebook
       - db
  minimal-jupyter-notebook:
    image: jupyter/minimal-notebook:latest
    environment:
      - GRANT_SUDO=yes
    ports:
      - 8888:8888
    volumes:
      - work:/home/jovyan/work
  db:
    image: 'postgres:9.6.3-alpine'
    container_name: psql_dataenv
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: psql_data_environment
      POSTGRES_USER: psql_user
      POSTGRES_PASSWORD: psql
      PGDATA: /opt/psql_data
    volumes:
      - /opt/psql_data
    restart: "no"